In [1]:
import numpy as np

In [2]:
from numpy import *

In [3]:
random = np.rand(4,4)

AttributeError: module 'numpy' has no attribute 'rand'

In [4]:
random.rand(4,4)

array([[ 0.65462459,  0.53194549,  0.24095596,  0.53299517],
       [ 0.19061765,  0.9277127 ,  0.33183445,  0.64683773],
       [ 0.54946758,  0.15563388,  0.69224846,  0.12673156],
       [ 0.84897358,  0.90375967,  0.9001279 ,  0.40429767]])

In [7]:
randMat = mat(random.rand(4,4))

In [8]:
randMat.I

matrix([[ -2.1082361 ,   1.54736383,  -2.62734758,  10.14342918],
        [ -2.64669372,   1.60941487,   1.93840812,  -2.7525901 ],
        [  3.12362455,  -0.38168322,   0.46576901,  -5.00591941],
        [  3.89281738,  -3.99007984,   3.49713925,  -8.10203146]])

In [9]:
randMat

matrix([[ 0.4365668 ,  0.14550677,  0.51539005,  0.17869134],
        [ 0.41005169,  0.39391503,  0.59795855,  0.01008529],
        [ 0.68911331,  0.5459116 ,  0.36353585,  0.45266055],
        [ 0.30526431,  0.11155323,  0.11006529,  0.15284915]])

In [10]:
invRandMat = randMat.I

In [11]:
randMat * invRandMat

matrix([[  1.00000000e+00,   5.55111512e-17,  -1.11022302e-16,
           4.44089210e-16],
        [  0.00000000e+00,   1.00000000e+00,   1.11022302e-16,
           0.00000000e+00],
        [ -1.66533454e-16,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00],
        [ -1.11022302e-16,  -5.55111512e-17,   0.00000000e+00,
           1.00000000e+00]])

In [12]:
myEye = randMat * invRandMat

In [13]:
myEye - eye(4)

matrix([[ -2.22044605e-16,   5.55111512e-17,  -1.11022302e-16,
           4.44089210e-16],
        [  0.00000000e+00,   0.00000000e+00,   1.11022302e-16,
           0.00000000e+00],
        [ -1.66533454e-16,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [ -1.11022302e-16,  -5.55111512e-17,   0.00000000e+00,
           4.44089210e-16]])